### ISSUE TITLE
[SUGGESTION] Bat friendly fire

### ISSUE THREAD

**Issue by srnyx** [Fulmineo64/CompanionBats#4]
Would be cool if you couldn't damage/kill your own bats.
This could be toggled by a server config setting maybe.

**Comment by Fulmineo64** [comment]
Hi srnyx,
I've always thought of implementing this feature as an accessory.
It's been in my idea list for quite a while now.

I never actually did it in the end because [this mod](https://www.curseforge.com/minecraft/mc-mods/the-loved-ones) does a great job at solving the problem.

If you still would like to have an accessory that does the exact thing, let me know ;)

Have a good day!

**Comment by srnyx** [comment]
> I never actually did it in the end because [this mod](https://www.curseforge.com/minecraft/mc-mods/the-loved-ones) does a great job at solving the problem.

The Loved Ones doesn't seem to be working for me (it works for all other pets).

**Comment by Fulmineo64** [comment]
Hi srnyx,
I just recently had the same question on Curseforge so I thought to update this issue as well.

It seems that [Project: Save the Pets!](https://www.curseforge.com/minecraft/mc-mods/projectsavethepets) works well with the Companion Bats mod, I tested it with the 1.17 with no apparent problems.

**Comment by srnyx** [comment]
> It seems that [Project: Save the Pets!](https://www.curseforge.com/minecraft/mc-mods/projectsavethepets) works well with the Companion Bats mod, I tested it with the 1.17 with no apparent problems.

I've recently shutdown my modded server.
This also means I'm leaving a majority of the Fabric/modded community. Sorry if this causes any complications.

*Thank you though.*
