### ISSUE TITLE
Strange glitch

### ISSUE THREAD

**Issue by srnyx** [Fulmineo64/CompanionBats#5]
For some reason, I have to click twice to get my back to "spawn."
And when I do, the server has a lag spike.

_This only started happening after updating to v1.13.0_

**Comment by Fulmineo64** [comment]
Hi, 
I just found and fixed an issue that happened only on multiplayer.
When testing though, I didn't experience the same side effects that you explained;
so the issue I fixed could be another one altogether.

The fix is available [here](https://www.curseforge.com/minecraft/mc-mods/companion-bats/files) in the latest releases (1.12.1 and 1.13.1).

Please let me know if this fixes your problem.
Thank you.

**Comment by srnyx** [comment]
> Please let me know if this fixes your problem.

Sorry, forgot to reply, it fixed it.
